# Generated by Django 5.1.6 on 2025-02-18 18:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tweets", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tweet",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveField(
            model_name="tweet",
            name="likes",
        ),
        migrations.AddField(
            model_name="follow",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="like",
            name="tweet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="likes",
                to="tweets.tweet",
            ),
        ),
        migrations.AlterField(
            model_name="tweet",
            name="content",
            field=models.TextField(max_length=280),
        ),
        migrations.AlterUniqueTogether(
            name="follow",
            unique_together={("user", "followed_user")},
        ),
        migrations.AlterUniqueTogether(
            name="like",
            unique_together={("user", "tweet")},
        ),
    ]
